### ISSUE TITLE
THANK YOU!!! (and how to parse)

### ISSUE THREAD

**Issue by 2br-2b** [nossbigg/catechism-ccc-json#1]
Thank you so much for posting this!!!  I have been looking all over for this, but haven't found it until now!!

I had one quick question.  How is the .json file formatted, or what is the structure of the json file?

For example, say I wanted to go to CCC 142.  How would I get to there given this JSON file?

I would have answered this myself, but the file is (understandably) too big for VS Code to handle.

Thank you so much!!!

**Comment by 2br-2b** [comment]
I'm playing around with it on https://github.com/2br-2b/CCC-test

**Comment by nossbigg** [comment]
@2br-2b: if you're familiar with TypeScript, the rough structure of the .json file is defined as per this type definition file [here](https://github.com/nossbigg/catechism/blob/master/src/store/cccTypedefs.ts).

With regards as to how to find a given CCC Reference number, the .json file itself doesn't provide that, but you should be able to generate a data structure to perform the reverse lookup. For what it's worth, i created a BST (of sorts) [(implementation here)](https://github.com/nossbigg/catechism/blob/master/src/cccMetaGenerator/makeRefRangeTree.ts) to do this exact reverse lookup in the sister project, [catechism](https://github.com/nossbigg/catechism), but you could always just use a simple map/dict to do the same thing 👍

Thanks for your interest!
